# Generated by Django 6.0.4 on 2026-04-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('UGT1A1', models.CharField(max_length=30)),
                ('CYP2D6', models.CharField(max_length=30)),
                ('ACE', models.CharField(max_length=30)),
                ('CYP3A5', models.CharField(max_length=30)),
            ],
        ),
    ]
